#!/bin/bash
IP_FILE="/tmp/ip_addr"
OLD_IP=""
[ -f $IP_FILE ] && OLD_IP=$(cat $IP_FILE) && echo "IP file exists" || echo "IP file doesn't exist"
CURR_IP=$(/usr/sbin/get_cur_ip)
[ "$OLD_IP" != "$CURR_IP" ] && echo "IP адрес изменен с $OLD_IP на $CURR_IP. Новая ссылка для просмотра видео с камер: http://$CURR_IP" | send_email "IP change to $CURR_IP" && echo "Email sent"
sudo echo $CURR_IP > $IP_FILE
