#!/bin/sh
EXEC_TIME=$(date +"%d-%m-%Y %H:%M:%S")
MOTION_DIR="/var/lib/motion/"
MD_SIZE=""
SIZE_METER=""
YANDEX_DISK_DIR="/home/orangepi/yandex.disk/"
YAD_AVAIL_SIZE=""
NEED_TO_CLEAN=true
ADDITIONAL_SIZE="5000"
transferSize () {
    METER=$(echo $1 | sed -e 's/[0-9,.]\{1,4\}//')
    echo $METER
    TOTAL_SIZE=$(echo $1 | sed -e 's/.$//')
    [ "$METER" = "G" ] && TOTAL_SIZE=$(echo "$TOTAL_SIZE*1000000" | bc -l)
    [ "$METER" = "M" ] && TOTAL_SIZE=$(echo "$TOTAL_SIZE*1000" | bc -l)
    #Возвращаем целую часть
    return ${TOTAL_SIZE%%.*}
}

echo "Staring to sync with yandex disk at $EXEC_TIME"

if ! (mount | grep 'yandex.disk')
then echo "Mount yandex disk";
mount yandex.disk
fi

sleep 5
if (find "$MOTION_DIR" -type f -size -250k)
then echo "Deleting empty files";
find "$MOTION_DIR" -type f -size -250k | xargs sudo rm;
fi

MD_SIZE=$(du -sh $MOTION_DIR | awk '{print $1}')
transferSize $MD_SIZE
MD_SIZE=$?

echo $MD_SIZE

METER=""
YAD_AVAIL_SIZE=$(df -h | grep 'yandex.disk' | awk '{print $4}')
transferSize $YAD_AVAIL_SIZE
YAD_AVAIL_SIZE=$?

echo $YAD_AVAIL_SIZE

if ($NEED_TO_CLEAN)
then echo "Need to clean"
cd $YANDEX_DISK_DIR
diff=$(($YAD_AVAIL_SIZE-$MD_SIZE))
while [ $diff -lt $ADDITIONAL_SIZE ]
do
  before_diff=$(($YAD_AVAIL_SIZE-$MD_SIZE))
  ls -1rt | grep '[0-9]\{2\}' | head -1 | xargs sudo rm
  YAD_AVAIL_SIZE=$(df -h | grep 'yandex.disk' | awk '{print $4}')
  transferSize $YAD_AVAIL_SIZE
  YAD_AVAIL_SIZE=$?
  diff=$(($YAD_AVAIL_SIZE-$MD_SIZE))
  echo "File is deleted"
  if [ $before_diff = $diff ]
  then
    break
  fi
done
fi

if (find "$MOTION_DIR" -mmin +60 -type f)
then echo "Moving files";
find "$MOTION_DIR" -mmin +60 -type f | xargs -I % mv % /home/orangepi/yandex.disk/
fi
